INSERT INTO PuestoAccion(puestoId,accionId) VALUES(2,1);
INSERT INTO PuestoAccion(puestoId,accionId) VALUES(2,2);
INSERT INTO PuestoAccion(puestoId,accionId) VALUES(2,3);
INSERT INTO PuestoAccion(puestoId,accionId) VALUES(2,4);
INSERT INTO PuestoAccion(puestoId,accionId) VALUES(1,1);
INSERT INTO PuestoAccion(puestoId,accionId) VALUES(1,2);
INSERT INTO PuestoAccion(puestoId,accionId) VALUES(1,4);
INSERT INTO PuestoAccion(puestoId,accionId) VALUES(3,1);
INSERT INTO PuestoAccion(puestoId,accionId) VALUES(3,2);
